[global]
author=["arcfpga"]

[parse]
sourcefile=[ "mystston.cpp" ]
mustbe.machines=["mystston", "myststono", "myststonoi"]
skip.Bootlegs=true

[buttons]
names=[
    { machine="mystston", names="Fire,Kick" },
]

[dipsw]
delete=[{names=["Unused"]}]

[ROM]
regions=[
    { name="maincpu" },
    { name="fgtiles_sprites", start="JTFRAME_BA1_START" },
    { name="bgtiles", start="JTFRAME_BA2_START" },
    { name="proms", start="JTFRAME_PROM_START" },
]
order=["maincpu","fgtiles_sprites","bgtiles","proms"]
