//============================================================================
//  jtmystston_game — Game top module for Mysterious Stones (Technos 1984)
//  Connects main CPU (M6502), sound (dual AY8910 via jt49), and video
//  subsystems to the JTFRAME interface. Port list matches the real, verified
//  generated wrapper (cores/mystston/mister/jtmystston_game_sdram.v — do not
//  edit that file, it's auto-generated by `jtframe mem`) — every port name/
//  width here was cross-checked against its `u_game(...)` instantiation.
//  License: GPLv3
//============================================================================

module jtmystston_game(
    // jtframe_game_ports.inc already `include`s mem_ports.inc itself under
    // `ifdef JTFRAME_MEMGEN (auto-set whenever cfg/mem.yaml exists) — a
    // second explicit include here (copied from this file's earlier, broken
    // version) duplicated the whole port list and broke elaboration; see
    // cores/pspikes/hdl/jtpspikes_game.v for the correct, single-include
    // pattern this now matches.
    `include "jtframe_game_ports.inc"
);

    // ------------------------------------------------------------------
    // Clocks: JTFRAME_PXLCLK=6 (macros.def) means pxl_cen/pxl2_cen are
    // INPUTS here (see jtframe_common_ports.inc) — jtframe generates and
    // wires them in on its own from that macro, independent of mem.yaml's
    // clocks: section (see mem.yaml's own comment on why pxl_cen isn't
    // declared there too). Nothing to derive.
    // ------------------------------------------------------------------
    assign debug_view = 8'd0;

    // ------------------------------------------------------------------
    // Internal signals between submodules
    // ------------------------------------------------------------------
    wire [7:0] snd_latch, snd_sel;
    wire       snd_sel_we;
    wire [7:0] video_control, scroll_reg;
    wire       flip;
    wire [8:0] vcnt;

    // page_select = video_control[2]; fg_color = {video_control[0],
    // video_control[1]} (mystston.cpp's get_fg_tile_info(): color =
    // ((vc&1)<<1)|((vc&2)>>1), i.e. the two bits swapped, not a plain slice).
    wire        page_select = video_control[2];
    wire [1:0]  fg_color    = { video_control[0], video_control[1] };

    // Videoram write snoop (see mystston_scroll.v / mystston_video.v's port
    // comments — CPU-visible videoram is single-port BRAM, so the bg/fg
    // tile-code prefetchers keep their own shadow copies instead of sharing
    // the address bus with the CPU).
    wire [11:0] cpu_videoram_addr = videoram_addr;
    wire [7:0]  cpu_videoram_din  = videoram_din;
    wire        cpu_videoram_we   = videoram_we;
    wire [6:0]  cpu_spriteram_addr = spriteram_addr;
    wire [7:0]  cpu_spriteram_din  = spriteram_din;
    wire        cpu_spriteram_we   = spriteram_we;
    wire [4:0]  cpu_paletteram_addr = paletteram_addr;
    wire [7:0]  cpu_paletteram_din  = paletteram_din;
    wire        cpu_paletteram_we   = paletteram_we;

    // ------------------------------------------------------------------
    // Main CPU subsystem (6502)
    //
    // clk24, NOT clk: cen_cpu/cen_ay are declared under mem.yaml's clk24
    // domain, so their consumers must run on clk24 too (doc/clocks.md: "make
    // sure the right clock is used in the game module for each respective
    // cen"; cores/kunio/hdl/jtkunio_game.v clocks its jt65c02 main on clk24
    // for the same reason). Running this on clk while cen_cpu was a clk24
    // pulse made each enable last TWO clk cycles — the CPU advanced twice per
    // intended step and changed the SDRAM address mid-request, corrupting
    // multi-byte operand reads (the crash-loop seen both in simulation and on
    // real MiSTer hardware as flashing palette colors).
    // ------------------------------------------------------------------
    /* verilator tracing_off */
    mystston_main u_main(
        .clk            ( clk24          ),
        .rst            ( rst24          ),
        .cen_cpu        ( cen_cpu        ),

        .maincpu_addr   ( maincpu_addr   ),
        .maincpu_data   ( maincpu_data   ),
        .maincpu_cs     ( maincpu_cs     ),
        .maincpu_ok     ( maincpu_ok     ),

        .workram_addr   ( workram_addr   ),
        .workram_dout   ( workram_dout   ),
        .workram_din    ( workram_din    ),
        .workram_we     ( workram_we     ),

        .videoram_addr  ( videoram_addr  ),
        .videoram_dout  ( videoram_dout  ),
        .videoram_din   ( videoram_din   ),
        .videoram_we    ( videoram_we    ),

        .spriteram_addr ( spriteram_addr ),
        .spriteram_dout ( spriteram_dout ),
        .spriteram_din  ( spriteram_din  ),
        .spriteram_we   ( spriteram_we   ),

        .paletteram_addr( paletteram_addr),
        .paletteram_dout( paletteram_dout),
        .paletteram_din ( paletteram_din ),
        .paletteram_we  ( paletteram_we  ),

        .joystick1      ( joystick1[5:0] ),
        .joystick2      ( joystick2[5:0] ),
        .coin           ( coin           ),
        .cab_1p         ( cab_1p         ),
        .service        ( service        ),
        .dipsw          ( dipsw          ),
        .dip_pause      ( dip_pause      ),
        .LVBL           ( LVBL           ),

        .vcnt           ( vcnt           ),

        .video_control  ( video_control  ),
        .scroll_reg     ( scroll_reg     ),
        .flip           ( flip           ),

        .snd_latch      ( snd_latch      ),
        .snd_sel        ( snd_sel        ),
        .snd_sel_we     ( snd_sel_we     )
    );

    // ------------------------------------------------------------------
    // Sound subsystem (dual AY8910)
    // ------------------------------------------------------------------
    mystston_sound u_sound(
        .clk            ( clk24        ), // same clk24 domain as cen_ay — see u_main's clock comment
        .rst            ( rst24        ),
        .cen_ay         ( cen_ay       ), // independent 1.5MHz enable (cfg/mem.yaml), not derived from cen_cpu
        .snd_latch      ( snd_latch    ),
        .snd_sel        ( snd_sel      ),
        .snd_sel_we     ( snd_sel_we   ),
        .ay1            ( ay1          ),
        .ay2            ( ay2          )
    );

    // ------------------------------------------------------------------
    // Video subsystem (tilemaps + sprites + palette)
    // ------------------------------------------------------------------
    mystston_video u_video(
        .clk               ( clk               ),
        .rst               ( rst               ),
        .pxl_cen           ( pxl_cen           ),
        .pxl2_cen          ( pxl2_cen          ),

        .gfx_en            ( gfx_en            ),
        .flip              ( flip              ),
        .scroll_reg        ( scroll_reg        ),
        .page_select       ( page_select       ),
        .fg_color          ( fg_color          ),

        .cpu_videoram_addr ( cpu_videoram_addr ),
        .cpu_videoram_din  ( cpu_videoram_din  ),
        .cpu_videoram_we   ( cpu_videoram_we   ),

        .gfx1_addr         ( gfx1_addr         ),
        .gfx1_data         ( gfx1_data         ),
        .gfx1_cs           ( gfx1_cs           ),
        .gfx1_ok           ( gfx1_ok           ),

        .gfx2_addr         ( gfx2_addr         ),
        .gfx2_data         ( gfx2_data         ),
        .gfx2_cs           ( gfx2_cs           ),
        .gfx2_ok           ( gfx2_ok           ),

        .cpu_spriteram_addr( cpu_spriteram_addr),
        .cpu_spriteram_din ( cpu_spriteram_din ),
        .cpu_spriteram_we  ( cpu_spriteram_we  ),

        .cpu_paletteram_addr( cpu_paletteram_addr ),
        .cpu_paletteram_din ( cpu_paletteram_din  ),
        .cpu_paletteram_we  ( cpu_paletteram_we   ),
        .proms_addr        ( proms_addr        ),
        .proms_data        ( proms_data        ),

        .LHBL              ( LHBL              ),
        .LVBL              ( LVBL              ),
        .HS                ( HS                ),
        .VS                ( VS                ),
        .red               ( red               ),
        .green             ( green             ),
        .blue              ( blue              ),

        .vcnt              ( vcnt              )
    );

endmodule
