# mariobros_neptunoplus.sdc — timing constraints for the NeptUNO+ bridge
# Common structure shared by every NeptUNO+ bridge in this repo — see
# doc/porting-a-native-core.md §6a ("Shared .qpf/.qsf/.sdc template").
# clk_sys is generated by this bridge's own pll.v (48MHz from a direct 50MHz reference — see
# that file's own header comment). Unlike every SDRAM-backed core bridged so far, mario_top itself
# owns no PLL at all — there is exactly one PLL in this whole design, and it is bridge-owned by
# necessity, not in spite of §2.2's golden rule (which is about never adding a *second*,
# *redundant* PLL alongside a core-owned one — there is no core-owned one here to duplicate).

# ---- Clocks ----
create_clock -name {CLOCK_27} -period 20.000 [get_ports {CLOCK_27[0]}]
create_clock -name {SPI_SCK}  -period 41.666 -waveform { 20.8 41.666 } [get_ports {SPI_SCK}]

# ---- PLL clock derivation ----
derive_pll_clocks -create_base_clocks
derive_clock_uncertainty

# ---- PLL clock names ----
set sys_clk "pll|altpll_component|auto_generated|pll1|clk[0]"

# ---- SPI / IO-controller input delays ----
set_input_delay -add_delay -clock_fall -clock [get_clocks {CLOCK_27}] 1.000 [get_ports {CLOCK_27[0]}]
set_input_delay -add_delay -clock_fall -clock [get_clocks {SPI_SCK}]  1.000 [get_ports {CONF_DATA0}]
set_input_delay -add_delay -clock_fall -clock [get_clocks {SPI_SCK}]  1.000 [get_ports {SPI_DI}]
set_input_delay -add_delay -clock_fall -clock [get_clocks {SPI_SCK}]  1.000 [get_ports {SPI_SCK}]
set_input_delay -add_delay -clock_fall -clock [get_clocks {SPI_SCK}]  1.000 [get_ports {SPI_SS2}]
set_input_delay -add_delay -clock_fall -clock [get_clocks {SPI_SCK}]  1.000 [get_ports {SPI_SS3}]
set_input_delay -add_delay -clock_fall -clock [get_clocks {SPI_SCK}]  1.000 [get_ports {SPI_SS4}]

# ---- Other output delays (LED/AUDIO/VGA) ----
set_output_delay -add_delay -clock [get_clocks {SPI_SCK}] 1.000 [get_ports {SPI_DO}]
set_output_delay -add_delay -clock [get_clocks $sys_clk]  1.000 [get_ports {AUDIO_L}]
set_output_delay -add_delay -clock [get_clocks $sys_clk]  1.000 [get_ports {AUDIO_R}]
set_output_delay -add_delay -clock [get_clocks $sys_clk]  1.000 [get_ports {LED}]
set_output_delay -add_delay -clock [get_clocks $sys_clk]  1.000 [get_ports {VGA_*}]

# ---- Clock groups ----
set_clock_groups -asynchronous -group [get_clocks {SPI_SCK}] -group [get_clocks {pll|altpll_component|auto_generated|pll1|clk[*]}]

# ---- Multicycle paths ----
set_multicycle_path -to {VGA_*[*]} -setup 2
set_multicycle_path -to {VGA_*[*]} -hold 1

# ---- False paths (async relay signals) ----
set_false_path -from [get_ports {SD_MISO}]
set_false_path -from [get_ports {SD_SCK}]
set_false_path -from [get_ports {JOY_DATA}]
set_false_path -to   [get_ports {XJOY_DATA}]
set_false_path -to   [get_ports {JOY_CLK}]
set_false_path -to   [get_ports {JOY_LOAD}]
set_false_path -to   [get_ports {JOY_SELECT}]
